class StaticData {
  static const List monthList = [
    "Jan",
    "Feb",
    "Mar",
    "April",
    "May",
    "Jun",
    "Jul",
    "Aug",
    "Sep",
    "Oct",
    "Nov",
    "Dec"
  ];

  static Map badges = {
    "Guru": {
      "asset_path": "assets/guru.png",
    },
    "Bull of Wall Street": {
      "asset_path": "assets/bull_of_wall_street.png",
    },
    "Genius": {
      "asset_path": "assets/genius.png",
    },
    "Trusted User": {
      "asset_path": "assets/trusted_user.png",
    },
    "Challenger": {
      "asset_path": "assets/challenger.png",
    },
  };

  static Map leagues = {
    1: {
      "name": "Warren Buffet",
      "asset_path": "assets/warren_buffet.png",
    },
    2: {
      "name": "Jim Simmons",
      "asset_path": "assets/jim_simmons.png",
    },
    3: {
      "name": "Benjamin Graham",
      "asset_path": "assets/benjamin_graham.png",
    },
    4: {
      "name": "Bill Gross",
      "asset_path": "assets/bill_gross.png",
    },
    5: {
      "name": "John Templeton",
      "asset_path": "assets/john_templeton.png",
    },
    6: {
      "name": "Steve Mandel",
      "asset_path": "assets/steve_mandel.png",
    },
    7: {
      "name": "Peter Lynch",
      "asset_path": "assets/peter_lynch.png",
    },
    8: {
      "name": "George Soros",
      "asset_path": "assets/george_soros.png",
    },
    9: {
      "name": "Lei Zhang",
      "asset_path": "assets/lei_zhang.png",
    },
    10: {
      "name": "Rakesh Jhunjhunwala",
      "asset_path": "assets/rakesh_jhunjhunwala.png",
    },
  };

  static const callingCodes = [
    "+93",
    "+355",
    "+213",
    "+376",
    "+244",
    "+672",
    "+54",
    "+374",
    "+297",
    "+61",
    "+43",
    "+994",
    "+973",
    "+880",
    "+375",
    "+32",
    "+501",
    "+229",
    "+975",
    "+591",
    "+387",
    "+267",
    "+55",
    "+246",
    "+673",
    "+359",
    "+226",
    "+257",
    "+855",
    "+237",
    "+1",
    "+238",
    "+236",
    "+235",
    "+56",
    "+86",
    "+61",
    "+57",
    "+269",
    "+682",
    "+506",
    "+385",
    "+53",
    "+599",
    "+357",
    "+420",
    "+243",
    "+45",
    "+253",
    "+670",
    "+593",
    "+20",
    "+503",
    "+240",
    "+291",
    "+372",
    "+251",
    "+500",
    "+298",
    "+679",
    "+358",
    "+33",
    "+689",
    "+241",
    "+220",
    "+995",
    "+49",
    "+233",
    "+350",
    "+30",
    "+299",
    "+502",
    "+224",
    "+245",
    "+592",
    "+509",
    "+504",
    "+852",
    "+36",
    "+354",
    "+91",
    "+62",
    "+98",
    "+964",
    "+353",
    "+972",
    "+39",
    "+225",
    "+81",
    "+962",
    "+7",
    "+254",
    "+686",
    "+383",
    "+965",
    "+996",
    "+856",
    "+371",
    "+961",
    "+266",
    "+231",
    "+218",
    "+423",
    "+370",
    "+352",
    "+853",
    "+389",
    "+261",
    "+265",
    "+60",
    "+960",
    "+223",
    "+356",
    "+692",
    "+222",
    "+230",
    "+262",
    "+52",
    "+691",
    "+373",
    "+377",
    "+976",
    "+382",
    "+212",
    "+258",
    "+95",
    "+264",
    "+674",
    "+977",
    "+31",
    "+599",
    "+687",
    "+64",
    "+505",
    "+227",
    "+234",
    "+683",
    "+850",
    "+47",
    "+968",
    "+92",
    "+680",
    "+970",
    "+507",
    "+675",
    "+595",
    "+51",
    "+63",
    "+64",
    "+48",
    "+351",
    "+1-787",
    "+974",
    "+242",
    "+262",
    "+40",
    "+250",
    "+590",
    "+290",
    "+590",
    "+508",
    "+685",
    "+378",
    "+239",
    "+966",
    "+221",
    "+381",
    "+248",
    "+232",
    "+65",
    "+421",
    "+386",
    "+677",
    "+252",
    "+27",
    "+82",
    "+211",
    "+34",
    "+94",
    "+249",
    "+597",
    "+47",
    "+268",
    "+46",
    "+41",
    "+963",
    "+886",
    "+992",
    "+255",
    "+66",
    "+228",
    "+690",
    "+676",
    "+1-868",
    "+216",
    "+90",
    "+993",
    "+1-649",
    "+688",
    "+1-340",
    "+256",
    "+380",
    "+971",
    "+44",
    "+598",
    "+998",
    "+678",
    "+379",
    "+58",
    "+84",
    "+681",
    "+212",
    "+967",
    "+260",
    "+263",
  ];

  static List introductionScreenData = [
    {
      "logoBottomLine": "YOUR PERSONAL ASSET MANAGER",
      "firstPara": "",
      "image": "assets/landing_page_stars.png",
      "lastPara":
          "Invest with confidence on world’s leading Robo and Social Investment App.Built by licenced asset-manager with strong track record of outperforming markets"
    },
    {
      "logoBottomLine": "PERSONALIZED PORTFOLIOS",
      "firstPara":
          "Let globally licensed (SEC, SFC,  SEBI FPI) asset manager build a personalized portfolio for you based on your risk appetite and goals",
      "image": "assets/personalizedPortfolio.png",
      "lastPara":
          "…hire professional money managers with a great track record to build an institutional grade portfolio for you."
    },
    {
      "logoBottomLine": "MULTIPLE ASSET CLASSES",
      "firstPara":
          "Tell us if you have any preferences and we’ll customize your portfolio across global stocks, bonds, "
              "commodities, crypto, private equity, hedge fund, venture capital, impact investing and private deals.",
      "image": "assets/multipleAssets.png",
      "lastPara": "..and Yes! we pick  securities that you can engage with, "
          "not just mutual funds and ETFs like other Robos…and so no double fees on those."
    },
    {
      "logoBottomLine": "LEARN HOW TO INVEST BETTER",
      "firstPara":
          "Master investment concepts with our Adaptive Learning Investment module. "
              "Ask questions and participate in discussions while earning Auro Coins that can be redeemed for free stocks.",
      "image": "assets/invest.png",
      "lastPara": "…Learn investment principles used by the all-time greats"
    },
    {
      "logoBottomLine": "PITCH STOCK & PORTFOLIOS",
      "firstPara":
          "Pitch stocks and portfolios while building your own investment track record",
      "image": "assets/pitchStock.png",
      "lastPara":
          "…allow others to follow your investments and earn a cut of their profits"
    },
    {
      "logoBottomLine": "FOLLOW STAR INVESTORS",
      "firstPara":
          "Choose from and Invest in a wide selection of professionally managed portfolios.",
      "image": "assets/starInvestor.png",
      "lastPara": "…while you sit back and watch your wealth grow"
    }
  ];
}
